/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedJdaiRouteImport } from './routes/_authenticated/jdai'
import { Route as AuthenticatedDirectoryRouteImport } from './routes/_authenticated/directory'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedChannelsRouteImport } from './routes/_authenticated/channels'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedSalesIndexRouteImport } from './routes/_authenticated/sales.index'
import { Route as AuthenticatedKnowledgeIndexRouteImport } from './routes/_authenticated/knowledge.index'
import { Route as AuthenticatedBreaksIndexRouteImport } from './routes/_authenticated/breaks.index'
import { Route as AuthenticatedAttendanceIndexRouteImport } from './routes/_authenticated/attendance.index'
import { Route as AuthenticatedAnalyticsIndexRouteImport } from './routes/_authenticated/analytics.index'
import { Route as AuthenticatedSalesTeamRouteImport } from './routes/_authenticated/sales.team'
import { Route as AuthenticatedKnowledgeIdRouteImport } from './routes/_authenticated/knowledge.$id'
import { Route as AuthenticatedEmployeesIdRouteImport } from './routes/_authenticated/employees.$id'
import { Route as AuthenticatedChatConversationIdRouteImport } from './routes/_authenticated/chat.$conversationId'
import { Route as AuthenticatedChannelsChannelIdRouteImport } from './routes/_authenticated/channels.$channelId'
import { Route as AuthenticatedBreaksTeamRouteImport } from './routes/_authenticated/breaks.team'
import { Route as AuthenticatedAttendanceTeamRouteImport } from './routes/_authenticated/attendance.team'
import { Route as AuthenticatedAdminShiftsRouteImport } from './routes/_authenticated/admin.shifts'
import { Route as AuthenticatedAdminSalesSourcesRouteImport } from './routes/_authenticated/admin.sales-sources'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin.roles'
import { Route as AuthenticatedAdminKnowledgeRouteImport } from './routes/_authenticated/admin.knowledge'
import { Route as AuthenticatedAdminHolidaysRouteImport } from './routes/_authenticated/admin.holidays'
import { Route as AuthenticatedAdminEmployeesRouteImport } from './routes/_authenticated/admin.employees'
import { Route as AuthenticatedAdminDepartmentsRouteImport } from './routes/_authenticated/admin.departments'
import { Route as AuthenticatedAdminCentresRouteImport } from './routes/_authenticated/admin.centres'
import { Route as AuthenticatedAdminBreaksRouteImport } from './routes/_authenticated/admin.breaks'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedJdaiRoute = AuthenticatedJdaiRouteImport.update({
  id: '/jdai',
  path: '/jdai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDirectoryRoute = AuthenticatedDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChannelsRoute = AuthenticatedChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesIndexRoute = AuthenticatedSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeIndexRoute =
  AuthenticatedKnowledgeIndexRouteImport.update({
    id: '/knowledge/',
    path: '/knowledge/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBreaksIndexRoute =
  AuthenticatedBreaksIndexRouteImport.update({
    id: '/breaks/',
    path: '/breaks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceIndexRoute =
  AuthenticatedAttendanceIndexRouteImport.update({
    id: '/attendance/',
    path: '/attendance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsIndexRoute =
  AuthenticatedAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesTeamRoute = AuthenticatedSalesTeamRouteImport.update({
  id: '/sales/team',
  path: '/sales/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeIdRoute =
  AuthenticatedKnowledgeIdRouteImport.update({
    id: '/knowledge/$id',
    path: '/knowledge/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployeesIdRoute =
  AuthenticatedEmployeesIdRouteImport.update({
    id: '/employees/$id',
    path: '/employees/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatConversationIdRoute =
  AuthenticatedChatConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)
const AuthenticatedChannelsChannelIdRoute =
  AuthenticatedChannelsChannelIdRouteImport.update({
    id: '/$channelId',
    path: '/$channelId',
    getParentRoute: () => AuthenticatedChannelsRoute,
  } as any)
const AuthenticatedBreaksTeamRoute = AuthenticatedBreaksTeamRouteImport.update({
  id: '/breaks/team',
  path: '/breaks/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceTeamRoute =
  AuthenticatedAttendanceTeamRouteImport.update({
    id: '/attendance/team',
    path: '/attendance/team',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminShiftsRoute =
  AuthenticatedAdminShiftsRouteImport.update({
    id: '/admin/shifts',
    path: '/admin/shifts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSalesSourcesRoute =
  AuthenticatedAdminSalesSourcesRouteImport.update({
    id: '/admin/sales-sources',
    path: '/admin/sales-sources',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminKnowledgeRoute =
  AuthenticatedAdminKnowledgeRouteImport.update({
    id: '/admin/knowledge',
    path: '/admin/knowledge',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminHolidaysRoute =
  AuthenticatedAdminHolidaysRouteImport.update({
    id: '/admin/holidays',
    path: '/admin/holidays',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmployeesRoute =
  AuthenticatedAdminEmployeesRouteImport.update({
    id: '/admin/employees',
    path: '/admin/employees',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDepartmentsRoute =
  AuthenticatedAdminDepartmentsRouteImport.update({
    id: '/admin/departments',
    path: '/admin/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCentresRoute =
  AuthenticatedAdminCentresRouteImport.update({
    id: '/admin/centres',
    path: '/admin/centres',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBreaksRoute =
  AuthenticatedAdminBreaksRouteImport.update({
    id: '/admin/breaks',
    path: '/admin/breaks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/channels': typeof AuthenticatedChannelsRouteWithChildren
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/directory': typeof AuthenticatedDirectoryRoute
  '/jdai': typeof AuthenticatedJdaiRoute
  '/api/chat': typeof ApiChatRoute
  '/admin/breaks': typeof AuthenticatedAdminBreaksRoute
  '/admin/centres': typeof AuthenticatedAdminCentresRoute
  '/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/admin/holidays': typeof AuthenticatedAdminHolidaysRoute
  '/admin/knowledge': typeof AuthenticatedAdminKnowledgeRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/sales-sources': typeof AuthenticatedAdminSalesSourcesRoute
  '/admin/shifts': typeof AuthenticatedAdminShiftsRoute
  '/attendance/team': typeof AuthenticatedAttendanceTeamRoute
  '/breaks/team': typeof AuthenticatedBreaksTeamRoute
  '/channels/$channelId': typeof AuthenticatedChannelsChannelIdRoute
  '/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/employees/$id': typeof AuthenticatedEmployeesIdRoute
  '/knowledge/$id': typeof AuthenticatedKnowledgeIdRoute
  '/sales/team': typeof AuthenticatedSalesTeamRoute
  '/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/attendance/': typeof AuthenticatedAttendanceIndexRoute
  '/breaks/': typeof AuthenticatedBreaksIndexRoute
  '/knowledge/': typeof AuthenticatedKnowledgeIndexRoute
  '/sales/': typeof AuthenticatedSalesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/channels': typeof AuthenticatedChannelsRouteWithChildren
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/directory': typeof AuthenticatedDirectoryRoute
  '/jdai': typeof AuthenticatedJdaiRoute
  '/api/chat': typeof ApiChatRoute
  '/admin/breaks': typeof AuthenticatedAdminBreaksRoute
  '/admin/centres': typeof AuthenticatedAdminCentresRoute
  '/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/admin/holidays': typeof AuthenticatedAdminHolidaysRoute
  '/admin/knowledge': typeof AuthenticatedAdminKnowledgeRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/sales-sources': typeof AuthenticatedAdminSalesSourcesRoute
  '/admin/shifts': typeof AuthenticatedAdminShiftsRoute
  '/attendance/team': typeof AuthenticatedAttendanceTeamRoute
  '/breaks/team': typeof AuthenticatedBreaksTeamRoute
  '/channels/$channelId': typeof AuthenticatedChannelsChannelIdRoute
  '/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/employees/$id': typeof AuthenticatedEmployeesIdRoute
  '/knowledge/$id': typeof AuthenticatedKnowledgeIdRoute
  '/sales/team': typeof AuthenticatedSalesTeamRoute
  '/analytics': typeof AuthenticatedAnalyticsIndexRoute
  '/attendance': typeof AuthenticatedAttendanceIndexRoute
  '/breaks': typeof AuthenticatedBreaksIndexRoute
  '/knowledge': typeof AuthenticatedKnowledgeIndexRoute
  '/sales': typeof AuthenticatedSalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/channels': typeof AuthenticatedChannelsRouteWithChildren
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/directory': typeof AuthenticatedDirectoryRoute
  '/_authenticated/jdai': typeof AuthenticatedJdaiRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/admin/breaks': typeof AuthenticatedAdminBreaksRoute
  '/_authenticated/admin/centres': typeof AuthenticatedAdminCentresRoute
  '/_authenticated/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/_authenticated/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/_authenticated/admin/holidays': typeof AuthenticatedAdminHolidaysRoute
  '/_authenticated/admin/knowledge': typeof AuthenticatedAdminKnowledgeRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/sales-sources': typeof AuthenticatedAdminSalesSourcesRoute
  '/_authenticated/admin/shifts': typeof AuthenticatedAdminShiftsRoute
  '/_authenticated/attendance/team': typeof AuthenticatedAttendanceTeamRoute
  '/_authenticated/breaks/team': typeof AuthenticatedBreaksTeamRoute
  '/_authenticated/channels/$channelId': typeof AuthenticatedChannelsChannelIdRoute
  '/_authenticated/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/_authenticated/employees/$id': typeof AuthenticatedEmployeesIdRoute
  '/_authenticated/knowledge/$id': typeof AuthenticatedKnowledgeIdRoute
  '/_authenticated/sales/team': typeof AuthenticatedSalesTeamRoute
  '/_authenticated/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/_authenticated/attendance/': typeof AuthenticatedAttendanceIndexRoute
  '/_authenticated/breaks/': typeof AuthenticatedBreaksIndexRoute
  '/_authenticated/knowledge/': typeof AuthenticatedKnowledgeIndexRoute
  '/_authenticated/sales/': typeof AuthenticatedSalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pending-approval'
    | '/reset-password'
    | '/announcements'
    | '/channels'
    | '/chat'
    | '/dashboard'
    | '/directory'
    | '/jdai'
    | '/api/chat'
    | '/admin/breaks'
    | '/admin/centres'
    | '/admin/departments'
    | '/admin/employees'
    | '/admin/holidays'
    | '/admin/knowledge'
    | '/admin/roles'
    | '/admin/sales-sources'
    | '/admin/shifts'
    | '/attendance/team'
    | '/breaks/team'
    | '/channels/$channelId'
    | '/chat/$conversationId'
    | '/employees/$id'
    | '/knowledge/$id'
    | '/sales/team'
    | '/analytics/'
    | '/attendance/'
    | '/breaks/'
    | '/knowledge/'
    | '/sales/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pending-approval'
    | '/reset-password'
    | '/announcements'
    | '/channels'
    | '/chat'
    | '/dashboard'
    | '/directory'
    | '/jdai'
    | '/api/chat'
    | '/admin/breaks'
    | '/admin/centres'
    | '/admin/departments'
    | '/admin/employees'
    | '/admin/holidays'
    | '/admin/knowledge'
    | '/admin/roles'
    | '/admin/sales-sources'
    | '/admin/shifts'
    | '/attendance/team'
    | '/breaks/team'
    | '/channels/$channelId'
    | '/chat/$conversationId'
    | '/employees/$id'
    | '/knowledge/$id'
    | '/sales/team'
    | '/analytics'
    | '/attendance'
    | '/breaks'
    | '/knowledge'
    | '/sales'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pending-approval'
    | '/reset-password'
    | '/_authenticated/announcements'
    | '/_authenticated/channels'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/directory'
    | '/_authenticated/jdai'
    | '/api/chat'
    | '/_authenticated/admin/breaks'
    | '/_authenticated/admin/centres'
    | '/_authenticated/admin/departments'
    | '/_authenticated/admin/employees'
    | '/_authenticated/admin/holidays'
    | '/_authenticated/admin/knowledge'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/sales-sources'
    | '/_authenticated/admin/shifts'
    | '/_authenticated/attendance/team'
    | '/_authenticated/breaks/team'
    | '/_authenticated/channels/$channelId'
    | '/_authenticated/chat/$conversationId'
    | '/_authenticated/employees/$id'
    | '/_authenticated/knowledge/$id'
    | '/_authenticated/sales/team'
    | '/_authenticated/analytics/'
    | '/_authenticated/attendance/'
    | '/_authenticated/breaks/'
    | '/_authenticated/knowledge/'
    | '/_authenticated/sales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PendingApprovalRoute: typeof PendingApprovalRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/jdai': {
      id: '/_authenticated/jdai'
      path: '/jdai'
      fullPath: '/jdai'
      preLoaderRoute: typeof AuthenticatedJdaiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/directory': {
      id: '/_authenticated/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof AuthenticatedDirectoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/channels': {
      id: '/_authenticated/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AuthenticatedChannelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/': {
      id: '/_authenticated/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof AuthenticatedSalesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge/': {
      id: '/_authenticated/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof AuthenticatedKnowledgeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/breaks/': {
      id: '/_authenticated/breaks/'
      path: '/breaks'
      fullPath: '/breaks/'
      preLoaderRoute: typeof AuthenticatedBreaksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/': {
      id: '/_authenticated/attendance/'
      path: '/attendance'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AuthenticatedAttendanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/': {
      id: '/_authenticated/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AuthenticatedAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/team': {
      id: '/_authenticated/sales/team'
      path: '/sales/team'
      fullPath: '/sales/team'
      preLoaderRoute: typeof AuthenticatedSalesTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge/$id': {
      id: '/_authenticated/knowledge/$id'
      path: '/knowledge/$id'
      fullPath: '/knowledge/$id'
      preLoaderRoute: typeof AuthenticatedKnowledgeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees/$id': {
      id: '/_authenticated/employees/$id'
      path: '/employees/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof AuthenticatedEmployeesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$conversationId': {
      id: '/_authenticated/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof AuthenticatedChatConversationIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/channels/$channelId': {
      id: '/_authenticated/channels/$channelId'
      path: '/$channelId'
      fullPath: '/channels/$channelId'
      preLoaderRoute: typeof AuthenticatedChannelsChannelIdRouteImport
      parentRoute: typeof AuthenticatedChannelsRoute
    }
    '/_authenticated/breaks/team': {
      id: '/_authenticated/breaks/team'
      path: '/breaks/team'
      fullPath: '/breaks/team'
      preLoaderRoute: typeof AuthenticatedBreaksTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/team': {
      id: '/_authenticated/attendance/team'
      path: '/attendance/team'
      fullPath: '/attendance/team'
      preLoaderRoute: typeof AuthenticatedAttendanceTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/shifts': {
      id: '/_authenticated/admin/shifts'
      path: '/admin/shifts'
      fullPath: '/admin/shifts'
      preLoaderRoute: typeof AuthenticatedAdminShiftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/sales-sources': {
      id: '/_authenticated/admin/sales-sources'
      path: '/admin/sales-sources'
      fullPath: '/admin/sales-sources'
      preLoaderRoute: typeof AuthenticatedAdminSalesSourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/knowledge': {
      id: '/_authenticated/admin/knowledge'
      path: '/admin/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/holidays': {
      id: '/_authenticated/admin/holidays'
      path: '/admin/holidays'
      fullPath: '/admin/holidays'
      preLoaderRoute: typeof AuthenticatedAdminHolidaysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/employees': {
      id: '/_authenticated/admin/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/departments': {
      id: '/_authenticated/admin/departments'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AuthenticatedAdminDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/centres': {
      id: '/_authenticated/admin/centres'
      path: '/admin/centres'
      fullPath: '/admin/centres'
      preLoaderRoute: typeof AuthenticatedAdminCentresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/breaks': {
      id: '/_authenticated/admin/breaks'
      path: '/admin/breaks'
      fullPath: '/admin/breaks'
      preLoaderRoute: typeof AuthenticatedAdminBreaksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedChannelsRouteChildren {
  AuthenticatedChannelsChannelIdRoute: typeof AuthenticatedChannelsChannelIdRoute
}

const AuthenticatedChannelsRouteChildren: AuthenticatedChannelsRouteChildren = {
  AuthenticatedChannelsChannelIdRoute: AuthenticatedChannelsChannelIdRoute,
}

const AuthenticatedChannelsRouteWithChildren =
  AuthenticatedChannelsRoute._addFileChildren(
    AuthenticatedChannelsRouteChildren,
  )

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatConversationIdRoute: typeof AuthenticatedChatConversationIdRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatConversationIdRoute: AuthenticatedChatConversationIdRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedChannelsRoute: typeof AuthenticatedChannelsRouteWithChildren
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDirectoryRoute: typeof AuthenticatedDirectoryRoute
  AuthenticatedJdaiRoute: typeof AuthenticatedJdaiRoute
  AuthenticatedAdminBreaksRoute: typeof AuthenticatedAdminBreaksRoute
  AuthenticatedAdminCentresRoute: typeof AuthenticatedAdminCentresRoute
  AuthenticatedAdminDepartmentsRoute: typeof AuthenticatedAdminDepartmentsRoute
  AuthenticatedAdminEmployeesRoute: typeof AuthenticatedAdminEmployeesRoute
  AuthenticatedAdminHolidaysRoute: typeof AuthenticatedAdminHolidaysRoute
  AuthenticatedAdminKnowledgeRoute: typeof AuthenticatedAdminKnowledgeRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminSalesSourcesRoute: typeof AuthenticatedAdminSalesSourcesRoute
  AuthenticatedAdminShiftsRoute: typeof AuthenticatedAdminShiftsRoute
  AuthenticatedAttendanceTeamRoute: typeof AuthenticatedAttendanceTeamRoute
  AuthenticatedBreaksTeamRoute: typeof AuthenticatedBreaksTeamRoute
  AuthenticatedEmployeesIdRoute: typeof AuthenticatedEmployeesIdRoute
  AuthenticatedKnowledgeIdRoute: typeof AuthenticatedKnowledgeIdRoute
  AuthenticatedSalesTeamRoute: typeof AuthenticatedSalesTeamRoute
  AuthenticatedAnalyticsIndexRoute: typeof AuthenticatedAnalyticsIndexRoute
  AuthenticatedAttendanceIndexRoute: typeof AuthenticatedAttendanceIndexRoute
  AuthenticatedBreaksIndexRoute: typeof AuthenticatedBreaksIndexRoute
  AuthenticatedKnowledgeIndexRoute: typeof AuthenticatedKnowledgeIndexRoute
  AuthenticatedSalesIndexRoute: typeof AuthenticatedSalesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedChannelsRoute: AuthenticatedChannelsRouteWithChildren,
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDirectoryRoute: AuthenticatedDirectoryRoute,
  AuthenticatedJdaiRoute: AuthenticatedJdaiRoute,
  AuthenticatedAdminBreaksRoute: AuthenticatedAdminBreaksRoute,
  AuthenticatedAdminCentresRoute: AuthenticatedAdminCentresRoute,
  AuthenticatedAdminDepartmentsRoute: AuthenticatedAdminDepartmentsRoute,
  AuthenticatedAdminEmployeesRoute: AuthenticatedAdminEmployeesRoute,
  AuthenticatedAdminHolidaysRoute: AuthenticatedAdminHolidaysRoute,
  AuthenticatedAdminKnowledgeRoute: AuthenticatedAdminKnowledgeRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminSalesSourcesRoute: AuthenticatedAdminSalesSourcesRoute,
  AuthenticatedAdminShiftsRoute: AuthenticatedAdminShiftsRoute,
  AuthenticatedAttendanceTeamRoute: AuthenticatedAttendanceTeamRoute,
  AuthenticatedBreaksTeamRoute: AuthenticatedBreaksTeamRoute,
  AuthenticatedEmployeesIdRoute: AuthenticatedEmployeesIdRoute,
  AuthenticatedKnowledgeIdRoute: AuthenticatedKnowledgeIdRoute,
  AuthenticatedSalesTeamRoute: AuthenticatedSalesTeamRoute,
  AuthenticatedAnalyticsIndexRoute: AuthenticatedAnalyticsIndexRoute,
  AuthenticatedAttendanceIndexRoute: AuthenticatedAttendanceIndexRoute,
  AuthenticatedBreaksIndexRoute: AuthenticatedBreaksIndexRoute,
  AuthenticatedKnowledgeIndexRoute: AuthenticatedKnowledgeIndexRoute,
  AuthenticatedSalesIndexRoute: AuthenticatedSalesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PendingApprovalRoute: PendingApprovalRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
